// Import Assets
import defibeats from "../assets/defibeatscreenshot.png"
import abx from "../assets/abx.png"
import aiAliens from "../assets/ai_aliens.png"

const Projects = () => {
    return (
        <section className="projects">
            <h2>My Projects</h2>

            <div className="projects__cards">

           

                <div className="projects__card">
                    <h3>AI Aliens NFT</h3>
                    <img src={aiAliens} alt="aialiens Swap Page" />
                    <p>
                        An AI Generated artwork collection, written and minted on the Polygon Blockchain. 
                        This artwork is completed generated by AI, based on their interpretation of Aliens.

                        The NFTs are free, just pay gas
                    </p>

                    <a rel="noreferrer" href="https://ai-aliens-nft.vercel.app/ " target="_blank" className="button">Site</a>
                    <a rel="noreferrer" href="https://github.com/cocacolasante/ai_aliens_nft" target="_blank" className="button">Code</a>
                </div>

                <div className="projects__card">
                    <h3>DeFiBeat Music Marketplace (in development)</h3>
                    <img src={defibeats} alt="defi beats Landing Page" />
                    <p>
                        A fully decentralized, NFT based, music marketplace and social media plateform. 
                        Users can create their own profiles, display a status message, upload their own
                        songs, mint them to the blockchain and list them for sale.

                        Website Alpha coming soon
                    </p>

                    <a rel="noreferrer" href="https://broken-sun-4203.on.fleek.co/" target="_blank" className="button">Site</a>
                    <a rel="noreferrer" href="https://github.com/cocacolasante/defibeatsv2" target="_blank" className="button">Code</a>
                </div>

                <div className="projects__card">
                    <h3>ABX Naming Service</h3>
                    <img src={abx} alt="abx Landing Page" />
                    <p>
                        An ENS Naming Service. Mint your own ".abx" ENS on the Mumbai testnet!

                        

                        Test now on the Mumbai network!


                    </p>

                    <a rel="noreferrer" href="https://polygon-ibwgqp6bt-cocacolasante.vercel.app/" target="_blank" className="button">Site</a>
                    <a rel="noreferrer" href="https://github.com/cocacolasante/polygon_ens" target="_blank" className="button">Code</a>
                </div>


            </div>
        </section>
    );
}

export default Projects;